using Main.Features.Apps.Connectors.GoogleCalendar;
using Main.Features.Apps.Domain;
using DomainBookingEvent = Main.Features.Apps.Domain.BookingEvent;
using GCalBookingEvent = Main.Features.Apps.Connectors.GoogleCalendar.BookingEvent;
using GCalAttendee = Main.Features.Apps.Connectors.GoogleCalendar.BookingEventAttendee;

namespace Main.Features.Apps.Connectors.GoogleMeet;

/// <summary>
///     Adapts Google Calendar's event API to the generic <see cref="IConferenceLinkProvider" />
///     contract. Google Meet does not have its own API — meetings are generated by inserting a
///     Calendar event with <c>conferenceData.createRequest</c> + <c>conferenceDataVersion=1</c>;
///     the response carries the <c>hangoutLink</c> we surface as the join URL.
///     <para>
///         <see cref="CredentialAppSlug" /> returns <c>google-calendar</c> so the orchestrator
///         looks up the existing Calendar credential rather than a (non-existent) google-meet
///         credential. The Calendar event id doubles as the conferencing external id —
///         update and cancel forward to the Calendar event lifecycle so the host's calendar
///         stays consistent with the booking.
///     </para>
/// </summary>
public sealed class GoogleMeetConferenceLinkProvider(GoogleCalendarServiceFactory factory) : IConferenceLinkProvider
{
    public AppSlug Slug => GoogleMeetSlug.Slug;

    public AppSlug CredentialAppSlug => GoogleCalendarSlug.Slug;

    public async Task<ConferenceLink> CreateAsync(Credential credential, DomainBookingEvent input, CancellationToken cancellationToken)
    {
        var service = factory.Create(credential);
        var (eventId, joinUrl) = await service.CreateEventWithMeetLinkAsync(ToGCal(input), cancellationToken);
        // Google Meet does not return a separate password — the link itself carries the access
        // token. Surface as null so downstream UI doesn't render an empty "Password:" line.
        return new ConferenceLink(eventId, joinUrl, Password: null);
    }

    public async Task<ConferenceLink> UpdateAsync(Credential credential, string externalId, DomainBookingEvent input, CancellationToken cancellationToken)
    {
        var service = factory.Create(credential);
        await service.UpdateEventAsync(externalId, ToGCal(input), cancellationToken);
        // The hangout link is stable across event updates — we can't easily re-read it without
        // an extra GET. Returning the externalId with an empty join URL is intentional: the
        // scheduling layer reuses the persisted BookingReference.LinkUrl when updates succeed.
        return new ConferenceLink(externalId, JoinUrl: string.Empty, Password: null);
    }

    public Task CancelAsync(Credential credential, string externalId, CancellationToken cancellationToken)
    {
        var service = factory.Create(credential);
        return service.CancelEventAsync(externalId, cancellationToken);
    }

    private static GCalBookingEvent ToGCal(DomainBookingEvent input)
    {
        var attendees = input.Attendees
            .Select(a => new GCalAttendee(a.Email, a.Name))
            .ToArray();
        return new GCalBookingEvent(
            input.Title,
            input.Description,
            input.StartTime,
            input.EndTime,
            input.TimeZone,
            input.OrganizerEmail,
            input.OrganizerName,
            attendees,
            Location: null,
            ICalUid: input.ICalUid
        );
    }
}
