using Main.Features.Apps.Connectors.GoogleCalendar;
using Main.Features.Apps.Domain;
using Microsoft.Extensions.DependencyInjection;
using SharedKernel.Domain;

namespace Main.Features.Apps.Connectors.GoogleMeet;

/// <summary>
///     Installer for Google Meet. Unlike the other conferencing connectors, Google Meet does
///     NOT run its own OAuth flow: meeting links are generated by creating a Google Calendar
///     event with <c>conferenceData.createRequest</c>, reusing the host's existing
///     <c>google-calendar</c> <see cref="Credential" /> and scope.
///     <para>
///         <see cref="BeginInstallAsync" /> verifies the prerequisite (the user must have
///         already installed Google Calendar) and returns a stub redirect to our own callback so
///         the platform's install→callback contract is exercised end-to-end.
///         <see cref="CompleteInstallAsync" /> re-checks the prerequisite and returns a result
///         with <see cref="AppInstallCallbackResult.PersistCredential" /> set to <c>false</c>,
///         signalling the platform handler to create the <see cref="AppInstallation" /> row but
///         skip writing a duplicate <see cref="Credential" />.
///     </para>
///     <para>
///         Mirrors cal.com's <c>googlevideo</c> app (<c>_getAdd.ts</c>), which similarly piggy-
///         backs on the Google Calendar credential and never collects fresh OAuth tokens.
///     </para>
///     <para>
///         Registered as a singleton (the platform's <c>IAppRegistry</c> is singleton and caches
///         the slug→installer map). We therefore can't take a constructor dependency on the
///         request-scoped <see cref="ICredentialRepository" />; instead we resolve one inside a
///         fresh <see cref="IServiceScope" /> per call.
///     </para>
/// </summary>
public sealed class GoogleMeetInstaller(IServiceScopeFactory scopeFactory) : IAppInstaller
{
    public AppSlug Slug => GoogleMeetSlug.Slug;

    public async Task<AppInstallStartResult> BeginInstallAsync(AppInstallContext context, CancellationToken cancellationToken)
    {
        await EnsureGoogleCalendarInstalledAsync(context.UserId, cancellationToken);

        // Stub redirect to our own callback. The platform contract requires an authorize URL,
        // but Google Meet has no real OAuth flow — the caller redirects to /api/apps/google-meet/
        // /callback which lands in CompleteInstallAsync, where we re-check the prerequisite
        // and signal "AppInstallation only, no Credential".
        var redirectUrl = $"{context.RedirectUri}?state={Uri.EscapeDataString(context.State)}&code=reuse-google-calendar";
        return new AppInstallStartResult(redirectUrl, context.State);
    }

    public async Task<AppInstallCallbackResult> CompleteInstallAsync(
        AppInstallCallbackContext context,
        CancellationToken cancellationToken
    )
    {
        await EnsureGoogleCalendarInstalledAsync(context.UserId, cancellationToken);

        // No fresh credential to persist: Google Meet reuses the Google Calendar credential.
        // The platform's CompleteAppInstallHandler reads PersistCredential=false and creates
        // only the AppInstallation row.
        return new AppInstallCallbackResult(string.Empty, PersistCredential: false);
    }

    public Task UninstallAsync(TenantId tenantId, UserId userId, string encryptedKey, CancellationToken cancellationToken)
    {
        // No-op: there is no google-meet Credential to remove (we never created one), and we
        // must NOT touch the google-calendar credential because Calendar may still be in use
        // independently. The platform handler removes the AppInstallation row.
        _ = tenantId;
        _ = userId;
        _ = encryptedKey;
        _ = cancellationToken;
        return Task.CompletedTask;
    }

    private async Task EnsureGoogleCalendarInstalledAsync(UserId userId, CancellationToken cancellationToken)
    {
        using var scope = scopeFactory.CreateScope();
        var credentialRepository = scope.ServiceProvider.GetRequiredService<ICredentialRepository>();
        var calendarCredential = await credentialRepository.GetForUserAsync(userId, GoogleCalendarSlug.Slug, cancellationToken);
        if (calendarCredential is null) throw new GoogleMeetPrerequisiteMissingException();
    }
}

/// <summary>
///     Thrown when a user attempts to install Google Meet without first installing the Google
///     Calendar connector. Surfaces as a 412 Precondition Failed at the API boundary once the
///     platform install handler grows explicit prerequisite mapping — once that wiring lands,
///     the platform can catch this exception and translate it. Deferred wiring is intentional
///     and tracked (mirrors the deferral noted on <c>GoogleCalendarNotConfiguredException</c>).
/// </summary>
public sealed class GoogleMeetPrerequisiteMissingException()
    : InvalidOperationException("Google Calendar must be installed before Google Meet — Google Meet reuses the Google Calendar credential.");
